# Generated by Django 5.2 on 2025-05-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0002_alter_ott_logo_url_alter_ott_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='link_url',
            field=models.URLField(blank=True, help_text='OTT 플랫폼 영화 상세페이지로 이동할 수 있는 URL입니다 (선택사항)', verbose_name='바로가기 링크 URL'),
        ),
    ]
