# Generated by Django 5.2 on 2025-05-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardcategory_boardpost_category_boardcommentlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='슬러그'),
        ),
    ]
