# Generated by Django 5.2 on 2025-05-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boardcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='슬러그'),
        ),
    ]
