# Generated by Django 5.2 on 2025-05-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewhistory',
            name='previous_rating',
            field=models.FloatField(),
        ),
    ]
