# Generated by Django 5.2 on 2025-05-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_reviewhistory_previous_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewLike',
        ),
    ]
