name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  DJANGO_SETTINGS_MODULE: config.settings
  PYTHON_VERSION: '3.11'

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          for i in {1..20}; do
            PGPASSWORD=password psql -h db -U user -d test_db -c "SELECT 1;" && break
            echo "Postgres not ready yet..."
            sleep 3
          done
          PGPASSWORD=password psql -h db -U user -d test_db -c "SELECT 1;" || exit 1

      - name: Run Django migrations
        run: python manage.py migrate
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          DB_HOST: db
          DB_PORT: 5432

      - name: Run Django unit tests
        run: python manage.py test
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          DB_HOST: db
          DB_PORT: 5432