name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  DJANGO_SETTINGS_MODULE: config.settings
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '20'

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # DB 초기화 대기 (최소 15초, 필요 시 늘릴 것)
      - name: Wait for DB to be ready
        run: sleep 20

      - name: Debug DB hostname
        run: nslookup db || echo "DB host not resolved"

      - name: Run Django migrations
        env:
          DATABASE_URL: postgres://user:password@db:5432/test_db
        run: python manage.py migrate

      - name: Run Django unit tests
        env:
          DATABASE_URL: postgres://user:password@db:5432/test_db
        run: python manage.py test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: |
          if [ -f node_modules/.bin/eslint ]; then
            npm run lint || true
          fi

      - name: Build (React)
        run: npm run build

      # (옵션) React 테스트 실행
      # - name: Run React tests
      #   run: npm test -- --watchAll=false

  docker:
    if: github.ref == 'refs/heads/main'
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/advanced-project-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/advanced-project-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/advanced-project-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/advanced-project-frontend:latest

      # (옵션) docker-compose build/push, ghcr.io 푸시 등 확장 가능

  # (옵션) 실제 서버 배포 단계 추가 예시
  # deploy:
  #   if: github.ref == 'refs/heads/main'
  #   needs: [docker]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: SSH 배포
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.DEPLOY_HOST }}
  #         username: ${{ secrets.DEPLOY_USER }}
  #         key: ${{ secrets.DEPLOY_KEY }}
  #         script: |
  #           cd /home/your-app
  #           docker-compose pull
  #           docker-compose up -d